version: "3.9"

services:
  backend:
    container_name: backend
    image: tucacon/voz_backend
    build: .
    ports:
      - "8000:8000"
    env_file: ".env"
    networks:
      - voz_net

  frontend:
    container_name: frontend
    image: tucacon/voz_frontend
    build:
      context: ./front-end
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    networks:
      - voz_net
    depends_on:
      - backend
    
  n8n:
    container_name: n8n
    image: n8nio/n8n:1.110.2
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE="Europe/Helsinki"
      - TZ="Europe/Helsinki"
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_ENCRYPTION_KEY=17b445402c9acd43ad1368b1e052b6b08da7376036dcae1e
      - N8N_RUNNERS_ENABLED=false
      - N8N_DEFAULT_CORS=TRUE
      - N8N_CORS_ALLOW_ORIGIN="*"
    volumes:
      - n8n_data:/home/node/.n8n
      - ./n8n_config:/home/node/config
    depends_on:
      - backend
      - frontend
    networks:
      - voz_net

networks:
  voz_net:
    driver: bridge

    
volumes:
  n8n_data:
